### ISSUE TITLE
Bridge west of Shilo Village wrong texture

### ISSUE THREAD

**Issue by dylliewillie** [RS117/RLHD#166]
**Describe the bug**
Bridge west of Shilo Village texture is supposed to be wood. Instead it shows some kind of stone texture.

**Screenshots**
Before
![before](https://user-images.githubusercontent.com/14276110/138562212-939bbbcf-e1c6-41af-93ad-36e36a6532f5.png)
After
![after](https://user-images.githubusercontent.com/14276110/138562211-320a41ad-1f78-4356-81c6-fabe9a144e91.png)

**Environment (please complete the following information):**
 - OS: Windows 10.0.19042 Build 19042
 - RuneLite version: 1.7.27
 - Launcher version: 1.6.0

**Comment by keyosk** [comment]
I've confirmed if you disable the Ground Textures config, this discolored bridge looks "normal". I'm still trying to understand the root cause, but it appears to be happening in this conditional, if the 4 assignments to `swMaterial, seMaterial, nwMaterial, neMaterial` are commented out, the bridge looks "normal": https://github.com/RS117/RLHD/blob/31aef4a61a8a3f7c21f30859525097989604bcad/src/main/java/rs117/hd/SceneUploader.java#L399-L430

<img width="875" alt="image" src="https://user-images.githubusercontent.com/1281388/157380969-69eeb428-0637-43a8-b0c4-b5bf0ed7c7d6.png">
