### ISSUE TITLE
Client won't stay on: Windows 10/HP

### ISSUE THREAD

**Issue by LNL94** [RS117/RLHD#19]
[client.log](https://github.com/RS117/RLHD/files/7156570/client.log)
Plugin will turn on but immediately turn off.

**Comment by jamesdileva** [comment]
Hey I have the same issue.
[client.log](https://github.com/RS117/RLHD/files/7156752/client.log)
Here is my log

**Comment by MFBread** [comment]
same issue here as well

**Comment by Squidthakid** [comment]
same issue here

**Comment by MinorM7** [comment]
same issue here. Any fix?

**Comment by LNL94** [comment]
Is there anything that I could do in the meantime to help? I'm know little to nothing about debugging but I'm willing to learn to rc in hd.

**Comment by Ferrariic** [comment]
This could be due to several reasons:
1. (Most Common) Your hardware is old and doesn't support the version of openGL that the plugin uses. Anything older than 2013 has a very high probability of not working.
Solution: As of right now there is nothing that can be done to fix this since the manufacturer would be the ones to give it newer openGL support with their drivers.

2. (Laptops with dual GPUs) If your laptop is a "gaming laptop", there's a good chance that runelite is trying to use the Integrated GPU instead of the high performance dedicated GPU.
Solution: You can set your GPU by following the guide at this link: https://support.lenovo.com/us/en/solutions/ht071102-how-to-switch-graphics-card-on-machines-running-nvidia-optimus-technology

If it still doesn't work ask a mod for help.

3. Out of date GPU drivers (unlikely but still plausible)
Solution: Update your drivers via your respective manufacturer.
Nvidia drivers: https://www.nvidia.com/Download/index.aspx OR if you have GeForceExperience installed you can update through there.
AMD drivers: https://www.amd.com/en/support

**Comment by LNL94** [comment]
Intel HD Graphics 4000 - updated and still no luck. Assuming that doesn't cut it?

**Comment by Myst** [comment]
RuneliteHD plugin requires OpenGL 4.3 and Intel HD Graphics doesn't support OpenGl 4.3.

**Comment by sosodev** [comment]
I'm going to close this in favor of #41 since it's a better description of the issue
