### ISSUE TITLE
error: Too many compute shader storage blocks (10/8)

### ISSUE THREAD

**Issue by JorisBlanken** [RS117/RLHD#4]
OS: Linux 5.11.0-34-generic
RuneLite version: 1.7.24
Oldschool revision: Rev 199
Launcher version: 2.1.5

#### GPU Info
```
09:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] (rev e7)
	Subsystem: Micro-Star International Co., Ltd. [MSI] Radeon RX 580 Armor 4G OC
	Kernel driver in use: amdgpu
	Kernel modules: amdgpu
```

#### client.log
```
2021-09-13 12:06:48 [Client] ERROR rs117.hd.HdPlugin - Error starting HD plugin
java.lang.RuntimeException: rs117.hd.ShaderException: error: Too many compute shader storage blocks (10/8)

	at rs117.hd.HdPlugin.lambda$startUp$0(HdPlugin.java:501)
	at rs117.hd.HdPlugin.invokeOnMainThread(HdPlugin.java:2363)
	at rs117.hd.HdPlugin.lambda$startUp$2(HdPlugin.java:440)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:195)
	at client.tq(client.java:43502)
	at client.aq(client.java)
	at at.b(at.java:406)
	at at.run(at.java:360)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: rs117.hd.ShaderException: error: Too many compute shader storage blocks (10/8)

	at rs117.hd.Shader.compile(Shader.java:94)
	at rs117.hd.HdPlugin.initProgram(HdPlugin.java:669)
	at rs117.hd.HdPlugin.lambda$startUp$0(HdPlugin.java:497)
	... 9 common frames omitted
```

**Comment by JorisBlanken** [comment]
Oddly, checking glxinfo yields:
```
GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS = 16
```

**Comment by pilino1234** [comment]
I'm experiencing this as well. I have a laptop with dual GPUs running Linux with these GPUs:

Integrated:
```
00:02.0 VGA compatible controller: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06) (prog-if 00 [VGA controller])
        Subsystem: Dell Device 05be
        [...snip]
        Kernel driver in use: i915
        Kernel modules: i915
```

Dedicated:
```
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Mars XTX [Radeon HD 8790M] (prog-if 00 [VGA controller])
        Subsystem: Dell Device 05be
        [...snip]
        Kernel driver in use: amdgpu
        Kernel modules: radeon, amdgpu
```

The integrated graphics card has `MAX_COMPUTE_SHADER_STORAGE_BLOCKS = 12`, while the dedicated GPU only has `MAX_COMPUTE_SHADER_STORAGE_BLOCKS = 8`, so it cannot store the 10 SSBOs used in [comp_common.glsl](https://github.com/RS117/RLHD/blob/master/src/main/resources/rs117/hd/comp_common.glsl). The original RuneLite GPU plugin works fine since it only uses 6 SSBOs there.  
I don't really know much about GL programming though, so not sure how feasible it would be to 'combine' some of these together to reduce the number of used SSBOs?

**Comment by JorisBlanken** [comment]
@pilino1234 I don't know much about GLSL either, but it seems like it can be done in certain cases: https://github.com/servo/pathfinder/issues/373

Still weird that it would complain about that if my GPU has 16 blocks, and it's the only GPU I have.

**Comment by JorisBlanken** [comment]
When manually building and testing the plugin through HdPluginTest.java, it runs just fine on my system.
Wondering whether this is a GPU configuration issue with RuneLite.

**Comment by JorisBlanken** [comment]
My issue was resolved by using the .AppImage from runelite.net instead of using the package published on snap.

**Comment by pilino1234** [comment]
Another user on the 117HD Discord also reported that using the AppImage solved their problem.  
I tried the "hard way" by upgrading Mesa to the latest version in the opensuse repos (21.2.6) which also solved the problem for me, because Mesa from version 20.2.0 has [a fix](https://gitlab.freedesktop.org/mesa/mesa/-/commit/5a05f9714bb5c78c01de39d2e6dc1ac5b351f8f1) for radeon cards to support up to 16 SSBO's. My Radeon card now reports `MAX_COMPUTE_SHADER_STORAGE_BLOCKS = 16`.

**Comment by JorisBlanken** [comment]
I worked with @Adam- from https://github.com/runelite.
The snap version should now work on channel "latest/edge", provided your GPU supports at least 10 SSBO's.
