### ISSUE TITLE
FPS drop when entering PoH

### ISSUE THREAD

**Issue by Rman887** [RS117/RLHD#8]
I get an FPS drop when I first enter my house:
![image](https://user-images.githubusercontent.com/6307183/133129982-b5d2fdfd-ab9d-4b8a-bde5-6cd4c3669754.png)

If I reset the plugin (off then on again), FPS goes back up:
![image](https://user-images.githubusercontent.com/6307183/133130320-76b1e7ba-50bf-4f0e-bc97-09c2beb94cd1.png)

Platform: Windows 10

**Comment by Spleen232** [comment]
I also found the same issue.

I typically run mostly 30-50 frames everywhere until I enter my house. At this moment the frames drop down to 17.

In order to get my frames back up I first disable the 117 plugin. I then enable the gpu plugin in runelite. I then re enable 117 plugin and my frames return to the normal 50 fps.

 my pc specs are as follows. 
Cpu: amd ryzen 5 3600 (6core)
Gpu: 3070
Ram:16gb ddr4
OS: Windows 10

I hope this helps!
![image](https://user-images.githubusercontent.com/90690724/133242406-65a37f17-407b-4950-80e2-d787d79a0af5.png)
![image](https://user-images.githubusercontent.com/90690724/133242469-69ec9daf-9cfa-4729-9410-c4fa3d95b954.png)
![20210914_223545](https://user-images.githubusercontent.com/90690724/133242965-430b9172-11e4-4a92-a785-831a54bb1e96.jpg)


Absolutely love the plugin,

Thank you so much for bringing this to the community and let me know if you need any other info!

Cheers,

**Comment by githubbingitup** [comment]
Same problem as the others. FPS lowers when entering POH and requires a plugin reset to fix.

I have tested it without any other plugins on. I've also tested it with all graphic settings in the HD plugin at minimum, to see if a specific effect was causing it. Nope.

Specs: i9 9900k, GTX 2080, 32gb ddr4 ram on windows 10.

**Comment by jeolives** [comment]
A potential fix is https://github.com/RS117/RLHD/pull/184 when it gets merged. However, it might not be integrated into the releases yet as there may be another alternative fix being developed.

**Comment by sosodev** [comment]
This was fixed with the merge of #184
